######################## default configuration ####################
baseURL = "https://00000000014A6343.pages.gitlab.lrz.de/alumni-network"
title = "STS-Munich.de"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Impressum"
URL = "impressum"
weight = 3

# [[menu.main]]
# name = "Contact"
# URL = "contact"
# weight = 4

# [[menu.main]]
# name = "Sample Page"
# URL = "sample-page"
# weight = 5

# only desktop menu
[[menu.desktop]]
name = "What's this about?"
URL = "/about"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "Tell us how your alumni network should be!"
author = "Matthias Meller"

# cookies
[params.cookies]
enable = false
expire_days = 2

# banner
[params.banner]
heading = "How would you like your alumni network to be?"
image = "images/title-image-kickoff-meeting.jpg"

# blog
[params.blog]
heading = "We believe students, PhDs and alumni of the Munich Center for Technology in Society need a space to connect beyond university and to bring the best of STS into the world. </br> </br> <b style='color:#0076bb'>Let's create our alumni network together.</b>"

# call to action
[params.call_to_action]
enable = true
title = "Thank you for having been at our virtual kick-off"
content = "We're thrilled and honoured that so many of you took the time to join us on November 12 for our virtual kick-off meeting. You couldn't make it? No worries, we'd be glad if you contribute nonetheless. Click below to join our WhatsApp channel in which we'll organise ourselves for the next steps ahead and getting the Alumni Network off the ground. <br><br> Also, if you like take a look at the slides from the kick-off meeting: <br> <i><a href='files/2020-11-12_MCTS Alumni Network_Kick-off_optimised.pdf'>Download the slides</a></i>"
button_label = "Join WhatsApp Group"
button_url = "https://chat.whatsapp.com/D1sEN1a70aFBdRDYTqkqyD"

# gallery
[params.gallery]
enable = false

[[params.gallery.gallery_item ]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "What's next: Join us!"
content = "Now we need you: your ideas, your support and your membership. To get this initiative truly started <b>we need a motivated and diverse group of founding members</b>. Check out the <a href='/alumni-network/about'>About</a> page here. <br><br> Want to join? Write us a quick <i>Like!</i> to <a href='mailto:alumni-network@mcts.tum.de'>alumni-network@mcts.tum.de</a>."
address = "Virtual Kick-off @ 8 pm via Zoom"
# hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
copyright = "&copy; 2020. Made with [Hugo](https://gohugo.io), [Twenty Twenty Theme](https://themes.gohugo.io/twenty-twenty-hugo/) and much ♥︎ from Matt, Dominik & Fabian."

############################# social site ########################
[params.social]
# yelp = "#"
# facebook = "#"
# twitter = "#"
# instagram = "#"
email = "alumni-network@mcts.tum.de"
# linkedin = "#"